config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts
  resources :users, only: :show
  get '/posts/genre_1/:id', to: "posts#genre_1"
  get 'following/:id',to: 'relationships#following', as:'following'
  get 'followerd/:id',to: 'relationships#followerd', as:'followerd'
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre_1.rb
class Genre1 < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: '飲食店'},
    {id: 3, name: '手作り'},
    {id: 4, name: 'コンビニ・スーパー'},
    {id: 5, name: 'その他'},
  ]
  include ActiveHash::Associations
  has_many :posts
end

app/models/genre_2.rb
class Genre2 < ActiveHash::Base
  self.data = [
    {id:1, name: '---'},
    {id:2, name: 'お弁当' },
    {id:3, name: '和食' },
    {id:4, name: '洋食' },
    {id:5, name: '中華' },
    {id:6, name: 'その他'},
  ]
  include ActiveHash::Associations
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre_1
  belongs_to :genre_2

  
  belongs_to :user
  has_one_attached :image

  validates :image, presence: true
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
         has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
         has_many :following_user, through: :follower, source: :followed
         has_many :follower_user, through: :followed, source: :follower

         def follow(user_id)
          follower.create(followed_id: user_id)
        end
        def unfollow(user_id)
          follower.find_by(followed_id: user_id).destroy
        end
        def following?(user)
          following_user.include?(user)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :text, :favorite ])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :move_to_index, :destroy ]
  before_action :move_to_index, only: :edit
  def index
    @post = Post.includes(:user).order("created_at DESC") 
    @posts = Post.all.page(params[:page]).per(8).includes(:user).order("created_at DESC") 
    @users = User.all
    @post_genre_1_2 = Post.where(genre_1_id: 2).limit(4).order("id": "desc")
    @post_genre_1_3 = Post.where(genre_1_id: 3).limit(4).order("id": "desc")
    @post_genre_1_4 = Post.where(genre_1_id: 4).limit(4).order("id": "desc")
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
   
  end
  
  def edit
  end
  def update
    if @post.update(post_params)
      
    redirect_to post_path(params[:id])
    else
      render :edit
    end

  end

  def destroy
    if current_user.id == @post.user_id
      @post.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def genre_1
    @post = Post.find_by(genre_1_id: params[:id])
    @posts = Post.where(genre_1_id: params[:id]).order('created_at DESC')
  end



  private

  def post_params
    params.require(:post).permit(:image, :title, :genre_1_id, :genre_2_id, :shop_name, :explanation, :self_assessment_id).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def move_to_index
    unless user_signed_in?  && current_user.id == @post.user_id 
      redirect_to action: :index
     end
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def following
    @user = User.find(params[:id])
  end
  def followerd
    @user = User.find(params[:id])
  end
  def follow
    current_user.follow(params[:id])
    redirect_to user_path
  end
  
  def unfollow
    current_user.unfollow(params[:id])
    redirect_to user_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Original31774</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= render "shared/header"%>
<div class=edit-form>
 <h1>記事編集</h1>
 <%= form_with model: @post,local: true do |f| %>

  <%#= render 'shared/error_messages', model: @post %>

  <div>タイトル
  <%= f.text_area :title, class:"posts-text", id:"post-title", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
  </div>

  <div class="img-upload">
      <div class="weight-bold-text">
        出品画像
        <span class="indispensable">必須</span>
      </div>

      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <div id="image-list"></div>
        <%= f.file_field :image, id:"post_image" %>
        </div>
        <div>ジャンル1
        <%= f.collection_select(:genre_1_id, Genre1.all, :id, :name, {} ,{class:"select-box", id:"postgenre1"}) %>
        </div>
        <div>ジャンル2
        <%= f.collection_select(:genre_2_id, Genre2.all, :id, :name, {} ,{class:"select-box", id:"postgenre2"}) %>
        </div>

        <div>店名
        <%= f.text_field :shop_name %>
        </div>

        <div>説明
         <%= f.text_area :explanation, class:"posts-text", id:"post-info", placeholder:"料理、食事の様子（必須 1,000文字まで)。" ,maxlength:"1000" %>
         </div>

         

       <div>
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
       </div>

    <% end %>
</div>

app/views/posts/genre_1.html.erb
<%= render "shared/header"%>
<div class="main">

<div class="container">
 <div class="genre_name">
  <%= "#{@post.genre_1.name}" %>
 </div>
 <ul class="row w-100 pt-50">
  <% @posts.each do |post| %>
   <%= link_to post_path(post.id) do %>
    <li class="col-md-4">
     <div>
     <%= image_tag post.image, class: "post-img" %>
     </div>
     <div>
     <%= post.title %>
     </div>
    </li>
   <% end %>
  <% end %>
 </ul>
</div>
</div>

app/views/posts/index.html.erb
<div class = 'main-2'>
 <%#  ヘッダー %>
  <header class = 'head-container' >
   <div class = 'title-contents'>
    <h1>ひるメシ</h1>
   </div>
   <div class = 'catch-contents'>
    <div class= "kye-comment">
    お昼何食べた？今日のお昼ご飯が見つかるかも！！
    </div>
   </div>
    <nav>
     <ul style="list-style: none;" class="list-inline">
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% if user_signed_in? %>
      <li class="list-menu"> <%= link_to '新規投稿', new_post_path %> </li>
      <li class="list-menu"><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
      <li class="list-menu"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <div>
      <li class="list-menu"><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      </div>
      <div>
      <li class="list-menu"><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      </div>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% end %>
     </ul>
     </nav>
   </header>
 <%# /ヘッダー %>
 <%# アプリケーション概要 %>
 <%# /アプリケーション概要 %>
 <%# 検索フォーム%>
 <%# /検索フォーム%>
 <%# ジャンル一覧 %>
 <%# /ジャンル一覧 %>
 <div class="box">
 <%# 記事一覧 %>
  <div class="container">
   <p class = 'new-post-all'>
   新着記事一覧
   </p>
   <ul class="row">
    <% @posts.each do |post| %>
    <%= link_to post_path(post.id) do %>
     <li class="border rounded m-3 text-center">
     <%= image_tag post.image, class: "post-img" %>
     <p class='post-name'>
     <%= post.title %>
     </p>
     </li>
       <% end %>
      <% end %>
     </ul>
    <%= paginate @posts %>
   </div>
 <%# /記事一覧 %>

 <%# 飲食店新着５〜６件 %>
 <div class="container">
 <h1>飲食店</h1>
 <ul class='row'>
 <% @post_genre_1_2.each do |post| %>
<%= link_to post_path(post.id) do %>
<li class="border border-primary rounded m-3 text-center">
<%= image_tag post.image, class: "post-img" %>
<p class='post-name'>
    <%= post.title %>
    </p>
</li>
<% end %>
<% end %>
</ul>
<div>
<%= link_to "もっと見る", "/posts/genre_1/2"%>
</div>
</div>


<%# /飲食店新着５〜６件 %>
<%# 手料理新着５〜６件 %>
<div class="container">
<h1>手料理</h1>
<ul class="row">
<% @post_genre_1_3.each do |post| %>
<%= link_to post_path(post.id) do %>
<li class="border border-primary rounded m-3">
<%= image_tag post.image, class: "post-img" %>
<p class='post-name'>
    <%= post.title %>
    </p>
</li>
<% end %>
<% end %>
</ul>
<div>
<%= link_to "もっと見る", "/posts/genre_1/3"%>
</div>
</div>

<%# /手料理新着５〜６件 %>
<%# コンビニ・スーパー テイクアウト 5~6件 %>
<div class="container">
<h1>テイクアウト・その他</h1>
<ul class="row">
<% @post_genre_1_4.each do |post| %>
<%= link_to post_path(post.id) do %>
<li class="border border-primary rounded m-3">
<%= image_tag post.image, class: "post-img" %>
<p class='post-name'>
    <%= post.title %>
    </p>
</li>
<% end %>
<% end %>
<%if @post_genre_1_4.ids.present? %>
<% end %>
</ul>
<div>
<%= link_to "もっと見る", "/posts/genre_1/4"%>
</div>
</div>
<%# /コンビニ・スーパー テイクアウト 5~6件 %>

</div>
<%# フォロー関係 %>

<%# /フォロー関係 %>
</div>
<%# footer %>
<%# /footer %>

app/views/posts/new.html.erb
<%= render "shared/header"%>
<div class=post-form>
 <h1>新規投稿記事</h1>
 <%= form_with model: @post,local: true do |f| %>

  <%#= render 'shared/error_messages', model: @post %>

  <div>タイトル
  <%= f.text_area :title, class:"posts-text", id:"post-title", placeholder:"タイトル（必須 40文字まで)", maxlength:"40" %>
  </div>

  <div class="img-upload">
      <div class="weight-bold-text">
        画像
        <span class="indispensable">必須</span>
      </div>

      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <div id="image-list"></div>
        <%= f.file_field :image, id:"post_image" %>
        </div>
        <div>ジャンル1
        <%= f.collection_select(:genre_1_id, Genre1.all, :id, :name, {} ,{class:"select-box", id:"postgenre1"}) %>
        </div>
        <div>ジャンル2
        <%= f.collection_select(:genre_2_id, Genre2.all, :id, :name, {} ,{class:"select-box", id:"postgenre2"}) %>
        </div>

        <div>店名
        <%= f.text_field :shop_name %>
        </div>

        <div>説明
         <%= f.text_area :explanation, class:"posts-text", id:"post-info", placeholder:"料理、食事の様子（必須 1,000文字まで)。" ,maxlength:"1000" %>
         </div>

         

       <div>
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
       </div>

    <% end %>
</div>

app/views/posts/show.html.erb
<%= render "shared/header"%>
<div class="main">
<div class="container d-flex flex-row">
<div class="explan">
<%# 記事の概要 %>
<table class="detail-table">
<tr>
 <th>タイトル</th>
 <td><%= @post.title %></td>
</tr>
<tr>
 <th>投稿者</th>
 <td><%= link_to "#{@post.user.nickname}", user_path(@post.user.id)%></td>
</tr>
<tr>
 <th>ジャンル1</th>
 <td><%= @post.genre_1.name %></td>
</tr>
<tr>
 <th>ジャンル２</th>
 <td><%= @post.genre_2.name %></td>
</tr>
<tr>
 <th>説明</th>
 <td><%= @post.explanation %></td>
</tr>

<div class="col-md-auto">
<%= image_tag @post.image, class: "image"%>
</div>
</table>
<%# /記事の概要 %>
 <%# 投稿ユーザーのみ記事の編集、削除ボタンが現れる %>
  <% if user_signed_in? && current_user.id == @post.user_id %>
  <%= link_to "編集", edit_post_path(@post) %>
  <%= link_to "記事削除", post_path(@post.id), method: :delete %>
  <% else %>
  <% end %>
  <%# /投稿ユーザーのみ記事の編集、削除ボタンが現れる %>
   <%# フォローする・削除 %>
  <%# /フォローする・削除 %>
<a herf="#">
前の記事
</a>
<a herf="#">
次の記事
</a>
<div>
<%= link_to "topページ", root_path%>
</div>
<%# コメント %>
<%# /コメント %>
</div>
</div>
</div>

app/views/relationships/followerd.html.erb
<%= render "shared/header"%>
<div class="main">
  <h2>フォロワー</h2>
<% @user.follower_user.where.not(id: @user.id).each do |user| %>
    <p>
      <%= link_to "#{user.nickname}", user_path(user) %>
      <%= link_to "見にいく", user_path(user) %>
    </p>
  <% end %>
  </div>

app/views/relationships/following.html.erb
<%= render "shared/header"%>
<div class="main">
<h2>フォローしてる人</h2>
  <% @user.following_user.where.not(id: @user.id).each do |user| %>
    <p>
      <%= "名前 #{user.nickname}" %>
      <%= link_to "見にいく", user_path(user) %>
    </p>
  <% end %>
  </div>

app/views/shared/_header.html.erb
<header class="second-header">
 <div class="heading">
  <h1 class= "title-name"><%= link_to 'ひるめし', root_path, class:"head-title" %></h1>
 </div>
 <div class="navber">
  <ul class="nav-lists">
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% if user_signed_in? %>
      <li class="menu-icon"> <%= link_to '新規投稿', new_post_path %> </li>
      <li class="menu-icon"><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
      <li class="menu-icon"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li class="menu-icon"><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li class="menu-icon"><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% end %>
     </ul>
 </div>
</header>

app/views/users/show.html.erb
<%= render "shared/header"%>
<div class="my-page">
<%# ユーザープロフィール %>
 <div class="my-data">
  <div class="my-name">
   <%= @user.nickname %>
  </div>
   <ul class="follow-bar">
    <li class="follow-menu">
    <%= link_to "#{@user.follower.count} フォロー中", following_path(@user.id) %>
    </li>
    <li class="follow-menu">
    <%= link_to "#{@user.followed.count} フォロワー", followerd_path(@user.id) %>
    </li>
     <% if user_signed_in? && current_user.id != @user.id %>
  <% if current_user.following?(@user) %>
    <li class="follow-menu"><%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST %></li>
  <% else %>
    <li class="follow-menu"><%= link_to 'フォローする', follow_path(@user.id), method: :POST %></li>
  <% end %>
<% end %>
   </ul>
   <div class="my-profile">
   <%= @user.text %>
   </div>
  
 </div>
<%# /ユーザープロフィール %>
<%# ログインユーザー自身のページだったら表示する %>
<%# 新規投稿ボタン %>

<%# /新規投稿ボタン %>
<%# フォローしてる人の新着記事 %>
<%# /フォロワーの新着記事 %>
<%# /ログインユーザー自身のページだったら表示する %>
<%# 新着順自身の記事 %>
<div class="my-new-posts">
 <h2 class="page-heading">
        <%= "#{@user.nickname}さんの投稿記事"%>
      </h2>
 <ul class="my-posts">
  <% @posts.each do |post| %>
   <%= link_to post_path(post.id) do %>
    <li class="my-post">
     <div class="img-box">
     <%= image_tag post.image, class: "img-box" %>
     </div>
     <div class="title-name">
     <%= post.title %>
     </div>
    </li>
   <% end %>
  <% end %>
 </ul>
</div>

<%# /新着順自身の記事 %>
<%# カレンダー %>
<%# /カレンダー %>
</div>